### ISSUE TITLE
Cannot read properties of null (reading 'toLocal')

### ISSUE THREAD

**Issue by zhouccccc** [pixi-viewport/pixi-viewport#504]
Very nice to see the latest version released!!
When I upgrade to the latest version and wheel on the viewport， I found the problem as below.
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/7f0083f9-c032-4e08-8c7a-1fe439779e07">

the value of the red mark is null, but when I run the code as below, it works.
<img width="641" alt="image" src="https://github.com/user-attachments/assets/e35e7236-84a6-4aac-a48f-b31118469060">

So is it possible that there are extra 'parent' written in the code?

**Comment by lunarraid** [comment]
Can you please provide a minimal reproduction? The only situation I can conceive of where the parent's parent would be null is if the viewport isn't added to a container, but is still responding to wheel events (which doesn't sound like a valid state?). There may be an edge case setup that I haven't considered.

**Comment by lunarraid** [comment]
@zhouccccc @danielbarion Digging further into this, I realize that there was a change I made to support this very case that made it into the other plugin files but didn't make it into this one. It's still a strange case, but it definitely shouldn't throw an error. Let me toss up a PR shortly.

**Comment by lunarraid** [comment]
@danielbarion @zhouccccc Could you please confirm this handles the case you're running into before merging? I applied the same logic I had in the other plugins.

**Comment by zhouccccc** [comment]
> Can you please provide a minimal reproduction? The only situation I can conceive of where the parent's parent would be null is if the viewport isn't added to a container, but is still responding to wheel events (which doesn't sound like a valid state?). There may be an edge case setup that I haven't considered.

@lunarraid here is the minial reproduction in my case
https://codesandbox.io/p/sandbox/cm8z9t

**Comment by zhouccccc** [comment]
> @danielbarion @zhouccccc Could you please confirm this handles the case you're running into before merging? I applied the same logic I had in the other plugins.
> 
> (Though I would definitely be interested in hearing the setup that is causing the viewport to not have a container yet still be receiving events)

yes, thanks for your work. I think it was what I want.

**Comment by danielbarion** [comment]
I already merged the fix and it will be released with the following PR: https://github.com/pixi-viewport/pixi-viewport/pull/505

I'm waiting for @davidfig to merge it and to release a new patch version

**Comment by lunarraid** [comment]
@zhouccccc That link doesn't seem to be valid (or is private) so I am unable to see what you mean, but this sounds like a different issue. Feel free to open another issue with the behavior.

**Comment by zhouccccc** [comment]
> @zhouccccc That link doesn't seem to be valid (or is private) so I am unable to see what you mean, but this sounds like a different issue. Feel free to open another issue with the behavior.

ok I will open another issue
