### ISSUE TITLE
global.d.ts file not found after build

### ISSUE THREAD

**Issue by Evanfan77** [pixi-viewport/pixi-viewport#508]
I'm using latest version of pixi-viewport in angular. after build, it has error in dist/index.d.ts file. in first line, the reference file doesn't exist. if i remove this line. everything works. is there anything im missing in tsconfig settings or this is a bug?
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/069d554c-56b3-44e1-b667-2848d2795ab7">

**Comment by danielbarion** [comment]
that's weird, I'll take a look to see what happened, I just checked my node_modules and having the same TS error.

**Comment by danielbarion** [comment]
I created a PR to fix it, should be released soon, thanks for raising the issue!

**Comment by Evanfan77** [comment]
> I created a PR to fix it, should be released soon, thanks for raising the issue!

Thank you
